# Usando NumPy

NumPy significa "Python numérico". Es un módulo _open source_ de Python que proporciona cálculos matemáticos rápidos en arreglos y matrices. Dado que los arreglos y matrices son una parte esencial del ecosistema de aprendizaje automático, NumPy se usa con otros módulos de machines learning como Scikit-learn, Pandas, Matplotlib, TensorFlow, etc.

## Jugando con numpy
### Importando el módulo

In [1]:
import numpy as np

### Creando vectores

In [2]:
lista = [1,2,3,4]
vector = np.array([1,2,3,4])

In [3]:
print(vector)

[1 2 3 4]


In [5]:
vector_unos = np.ones(6)
print(vector_unos)

[1. 1. 1. 1. 1. 1.]


In [6]:
vector_ceros = np.zeros(10)
print(vector_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
vector_diag = np.diag(np.ones(3))
print(vector_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


type(vector)

## Jugando con Pandas

### Importando el módulo

In [1]:
import pandas as pd

### Creando un DataFrame de un diccionario

In [4]:
data = {'Nombre':['Enrique','Sofia','Carlos','Lucia'],'Edad':[24,31,29,42]}
df = pd.DataFrame(data)
df

Nombre  Edad
0  Enrique    24
1    Sofia    31
2   Carlos    29
3    Lucia    42

### Creando un DataFrame de un arreglo

In [6]:
data = [["Enrique",24],["Sofia",31],["Carlos",29],["Lucia",42]]
df = pd.DataFrame(data,columns=['Nombres','Edad'])
df

Nombres  Edad
0  Enrique    24
1    Sofia    31
2   Carlos    29
3    Lucia    42